-- 1. Players Table
CREATE TABLE IF NOT EXISTS public.players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  cover_image_url TEXT,
  photo_image_url TEXT,
  player_image_url TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Gallery Table
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  image_url TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  is_media_linked BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.1 Achievements Table (dedicated table for admin-managed home achievements)
CREATE TABLE IF NOT EXISTS public.achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_name TEXT UNIQUE NOT NULL,
  image_url TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.2 Hero Slides Table (dedicated table for admin-managed home hero slider)
CREATE TABLE IF NOT EXISTS public.hero_slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_name TEXT UNIQUE NOT NULL,
  image_url TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_players_is_active ON public.players(is_active);
CREATE INDEX IF NOT EXISTS idx_gallery_is_active ON public.gallery(is_active);
CREATE INDEX IF NOT EXISTS idx_gallery_is_media_linked ON public.gallery(is_media_linked);
CREATE INDEX IF NOT EXISTS idx_gallery_created_at ON public.gallery(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_achievements_is_active ON public.achievements(is_active);
CREATE INDEX IF NOT EXISTS idx_hero_slides_is_active ON public.hero_slides(is_active);
CREATE INDEX IF NOT EXISTS idx_contact_status ON public.contact_form_submissions(status);
CREATE INDEX IF NOT EXISTS idx_contact_created_at ON public.contact_form_submissions(created_at DESC);




-- 3. Contact Form Submissions (Leads) Table
CREATE TABLE IF NOT EXISTS public.contact_form_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  source TEXT DEFAULT 'website' NOT NULL,
  status TEXT DEFAULT 'new' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Page Views Table
CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_name TEXT UNIQUE NOT NULL,
  view_count INT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Admin Users Table (for dashboard login)
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed default admin user if missing (replace password after first login)
INSERT INTO public.admin_users (username, password, is_active)
SELECT 'admin', 'admin_password', true
WHERE NOT EXISTS (
  SELECT 1 FROM public.admin_users WHERE username = 'admin'
);

-- Optional: Enable Row Level Security (RLS) and define basic public read access
-- (Since your APIs use the Service Role Key for insertions, public access can just be READ ONLY)
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to players" ON public.players FOR SELECT USING (true);
CREATE POLICY "Allow public read access to gallery" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "Allow public read access to achievements" ON public.achievements FOR SELECT USING (true);
CREATE POLICY "Allow public read access to hero slides" ON public.hero_slides FOR SELECT USING (true);
CREATE POLICY "Allow public read access to page views" ON public.page_views FOR SELECT USING (true);